plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id 'net.darkhax.curseforgegradle'
    id 'com.modrinth.minotaur'
}

//Use the existing Neoforge data generator for resource pack data
def generatedResources = project(":neoforge").file("src/generated/resources")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

loom {
    //Use the Access Widener File in the Common project module
    def aw = project(':fabric').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

repositories {

    maven { url "https://maven.architectury.dev/" }

    // the repository for Cloth Config
    maven { url "https://maven.shedaniel.me/" }

    maven {
        url "https://cursemaven.com"
    }

    maven {
        name = "Mod Menu Maven"
        url = "https://maven.terraformersmc.com/"
    }

    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
}

dependencies {

    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
//        parchment("org.parchmentmc.data:parchment-${rootProject.parchment_minecraft_version}:${rootProject.parchment_version}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    // Fabric API. This is technically optional, but we need this for Forge Config API Port
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"


    // Forge Config API Port
//    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${rootProject.forge_config_api_port_version}"
//    include "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${rootProject.forge_config_api_port_version}"

    modApi("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    include "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"

    modCompileOnly("com.terraformersmc:modmenu:${rootProject.mod_menu_version}") {
        transitive(false)
    }
    modRuntimeOnly("com.terraformersmc:modmenu:${rootProject.mod_menu_version}")

//    common(project(path: ":common", configuration: "namedElements")) { transitive false }
//    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }

}

/* IntelliJ Project Import
 * The Mixin annotation process does not have an obfuscation source when running through the IntelliJ compiler,
 * Thus we have to prevent it from being activated as part of importing this Gradle project into IntelliJ.
 */
if (System.getProperty("idea.sync.active") == "true") {
    afterEvaluate {
        tasks.withType(JavaCompile).all {
            it.options.annotationProcessorPath = files()
        }
    }
}

//shadowJar {
//    exclude "architectury.common.json"
//    configurations = [project.configurations.shadowCommon]
//    archiveClassifier = "dev-shadow"
//}

//remapJar {
//    injectAccessWidener = true
//    inputFile.set shadowJar.archiveFile
//    dependsOn shadowJar
//    archiveClassifier.set(null)
//}

//jar {
//    archiveClassifier.set("dev")
//}

//sourcesJar {
//    def commonSources = project(":common").sourcesJar
//    dependsOn commonSources
//    from commonSources.archiveFile.map { zipTree(it) }
//}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

if (System.getenv().CURSEFORGE_PUBLISH) {
    task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
        apiToken = System.getenv().CURSEFORGE_PUBLISH

        def mainFile = upload(curseforge_id_fabric, remapJar)
        mainFile.releaseType = 'release'
        mainFile.addGameVersion "Fabric"
        mainFile.addGameVersion "${minecraft_version}"
        mainFile.addGameVersion "Java 21"
        mainFile.addGameVersion('Client')

        mainFile.changelog = file("$project.rootDir/changelog.md")
        mainFile.changelogType = 'markdown'

        mainFile.addRequirement("fabric-api", "cloth-config")
    }
}


if (System.getenv().MODRINTH_PUBLISH) {
    String fileContents = file("$project.rootDir/changelog.md").text
    modrinth {
        token = System.getenv().MODRINTH_PUBLISH
        projectId = modrinth_id
        versionType = "release"
        versionName = "${mod_name}-${project.name}-${minecraft_version}"
        versionNumber = project.version
        uploadFile = remapJar
        changelog = fileContents
        gameVersions = ["${minecraft_version}"]
        loaders = ["fabric"]

        dependencies {
            required.project "fabric-api"
            required.project "cloth-config"
        }
    }
}