plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

//Use the existing Neoforge data generator for resource pack data
def generatedResources = project(":neoforge").file("src/generated/resources")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

loom {
    //Use the Access Widener File in the Fabric project module
    def aw = project(':fabric').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    //Remove mixin refmap config: Loom always handled refmaps for us but now it configures it a different way so the config is no longer needed
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

repositories {

    // the repository for Cloth Config
    maven { url = uri("https://maven.shedaniel.me/") }

    maven {
        url = uri("https://cursemaven.com")
    }

    maven {
        name = "Mod Menu Maven"
        url = uri("https://maven.terraformersmc.com/")
    }

    maven {
        name = "Fuzs Mod Resources"
        url = uri("https://raw.githubusercontent.com/Fuzss/modresources/main/maven/")
    }
}

dependencies {

    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    // Fabric API. This is technically optional, but we need this for Forge Config API Port and Cloth Config
    implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"


    // Forge Config API Port
//    api "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${rootProject.forge_config_api_port_version}"
//    include "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${rootProject.forge_config_api_port_version}"

    api("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    include "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"

    compileOnly("com.terraformersmc:modmenu:${rootProject.mod_menu_version}") {
        transitive(false)
    }
    runtimeOnly("com.terraformersmc:modmenu:${rootProject.mod_menu_version}")

}

/* IntelliJ Project Import
 * The Mixin annotation process does not have an obfuscation source when running through the IntelliJ compiler,
 * Thus we have to prevent it from being activated as part of importing this Gradle project into IntelliJ.
 */
if (System.getProperty("idea.sync.active") == "true") {
    afterEvaluate {
        tasks.withType(JavaCompile).all {
            it.options.annotationProcessorPath = files()
        }
    }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}