plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.7-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.52-beta' apply false
//    id "me.shedaniel.unified-publishing" version "0.1.+"
}

allprojects {
    apply plugin: "maven-publish"

    version = "${rootProject.mod_version}-${rootProject.minecraft_version}"
    group = rootProject.maven_group

    repositories {
        maven {
            url "https://cursemaven.com"
        }

        maven {
            name = "Forge Config API Port"
            url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
        }

        maven {
            name = "Cloth Config Maven"
            url = "https://maven.shedaniel.me/"
        }

        maven {
            name = "Mod Menu Maven"
            url = "https://maven.terraformersmc.com/"
        }

        maven { url 'https://jitpack.io' }

        flatDir {
            dirs '../modlibs'
        }

    }

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 21
    }

}

//task publishMeEverywhere(){
//    dependsOn ':neoforge:publishUnified'
//    dependsOn ':fabric:publishUnified'
//    dependsOn ':forge:publishUnified'
//}