# Gradle
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

#Project
java_version=21

# Mod Properties
jar_name=Boat-Item-View
mod_id=boatiview
mod_version=0.0.6
maven_group=me.soapsuds
minecraft_version=1.21.9
archives_base_name=boatiview
resource_pack_format=69

# Multiloader Properties

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.9-20250930.151910

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft_version=1.21.8
parchment_version=2025.09.14

enabled_platforms=neoforge,fabric,forge

#Mod Information

mod_name=Boat Item View
# Add "," between entries. Don't add quotation marks to the first and last characters.
mod_author=50ap5ud5
credits=Treblero, for the original idea.
mod_description=The Boat Item View mod allows you to view your held items whilst sitting in a moving boat.
homepage=https://github.com/50ap5ud5/BoatItemView
sources=https://github.com/50ap5ud5/BoatItemView
logo_file=icon.png
issue_tracker_url=https://github.com/50ap5ud5/BoatItemView/issues
license=https://github.com/50ap5ud5/BoatItemView/blob/1.21.x-multiloader/LICENSE


#Fabric
main_mod_class=me.soapsuds.boatiview.fabric.BoatItemViewImpl
mod_menu_integration_class=me.soapsuds.boatiview.fabric.config.ConfigModMenuIntegration

fabric_loader_version=0.17.2
#Fabric API version
##Required for Forge Config API
fabric_api_version=0.133.14+1.21.9
fabric_api_version_range=>=0.133.14+1.21.9
fabric_loader_version_range=>=0.17.2
fabric_minecraft_version_range=>=1.21.9 <=1.22
fabric_java_version_range=>=21
yarn_mappings=1.21.9+build.1

#Neoforge
neoforge_version=21.9.3-beta
neoforge_version_range=[21.9.1-beta,)
neoforge_loader_version_range=[4,)
neoforge_java_version_range=[21,)
neoforge_minecraft_version_range=[1.21.9, 1.22)

#Forge
forge_version=59.0.0
forge_version_range=[59.0.0,)
forge_loader_version_range=[0,)
forge_minecraft_version_range=[1.21.9, 1.22)

# Common dependencies
forge_config_api_port_version=21.5.1
mixin_version=0.8.5
mixin_extras_version=0.4.1

#Fabric Dependencies only for compile
cloth_config_version=19.0.147
mod_menu_version=15.0.0-beta.3

#Neoforge Dependencies only for runtime
configured_version=6023971

#Publishing
curseforge_id_forge=482444
curseforge_id_fabric=482160
modrinth_id=BdKIyOLe