# Gradle
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

#Project
java_version=25

# Mod Properties
jar_name=Boat-Item-View
mod_id=boatiview
mod_version=0.0.9
maven_group=me.soapsuds
minecraft_version=26.1
archives_base_name=boatiview
# pack_format is optional for resource pack version 69.0 and above i.e. MC 1.21.9 (Resource Pack 69.0) but mandatory for resource pack version 65 and below. i.e. MC 1.21.8 (Resource Pack 64. Resource 65 was a 1.21.9 snapshot development version).
resource_pack_format=84
# min_format is mandatory for resource pack version 69.0 and above i.e. MC 1.21.9 (Resource Pack 69.0). Allows minor versions. Array indicates a particular minor version [74, 1]. Single integer means major version e.g. 74 = [74, 0]
resource_pack_min_format=84
# max_format is mandatory for resource pack version 69.0 and above i.e. MC 1.21.9 (Resource Pack 69.0). Allows minor versions. Array indicates a particular minor version [74, 1]. Single integer means any minor version e.g. 9999
resource_pack_max_format=101.1

# Multiloader Properties

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1
mod_dev_gradle_version=2.0.141

enabled_platforms=neoforge,fabric,forge

#Mod Information

mod_name=Boat Item View
# Add "," between entries. Don't add quotation marks to the first and last characters.
mod_author=50ap5ud5
credits=Treblero, for the original idea.
mod_description=View your held items whilst you sit in a moving boat!
homepage=https://github.com/50ap5ud5/BoatItemView
sources=https://github.com/50ap5ud5/BoatItemView
logo_file=icon.png
issue_tracker_url=https://github.com/50ap5ud5/BoatItemView/issues
license=https://github.com/50ap5ud5/BoatItemView/blob/26.x-multiloader/LICENSE


#Fabric
main_mod_class=me.soapsuds.boatiview.fabric.BoatItemViewImpl
mod_menu_integration_class=me.soapsuds.boatiview.fabric.config.ConfigModMenuIntegration

loom_version=1.15-SNAPSHOT
fabric_loader_version=0.18.4
#Fabric API version
##Required for Forge Config API
fabric_api_version=0.144.3+26.1
fabric_api_version_range=>=0.144.3+26.1
fabric_loader_version_range=>=0.18.4
fabric_minecraft_version_range=>=26.1 <=26.2
fabric_java_version_range=>=21

#Neoforge
neoforge_version=26.1.0.7-beta
neoforge_version_range=[26.1.0.7-beta,)
neoforge_loader_version_range=[4,)
neoforge_java_version_range=[25,)
neoforge_minecraft_version_range=[26.1, 26.2)

#Forge
net.minecraftforge.gradle.merge-source-sets=true
forge_gradle_version=[7.0.17,8)
forge_version=62.0.4
forge_version_range=[62.0.4,)
forge_loader_version_range=[0,)
forge_minecraft_version_range=[26.1, 26.2)

# Common dependencies
forge_config_api_port_version=21.5.1
mixin_version=0.8.5
mixin_extras_version=0.4.1

#Fabric Dependencies only for compile
cloth_config_version=26.1.154
mod_menu_version=18.0.0-alpha.8

#Neoforge Dependencies only for runtime
configured_version=6023971

#Publishing
curseforge_id_forge=482444
curseforge_id_fabric=482160
modrinth_id=BdKIyOLe