modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
showAsResourcePack=true
showAsDataPack=true
issueTrackerURL = "${issue_tracker_url}" #optional
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="" #optional
displayURL = "${homepage}" #optional
logoFile = "${logo_file}" #optional
logoBlur=false
credits = "${credits}"
authors = "${mod_author}"
description = '''${mod_description}'''
#displayTest=""

[[accessTransformers]]
file="META-INF/accesstransformer_common.cfg"
[[mixins]]
config = "${mod_id}.common.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type="required"
versionRange = "${neoforge_version_range}"
ordering = "NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
side = "CLIENT" # Physical side this dependency is applied on - BOTH, CLIENT or SERVER
[[dependencies."${mod_id}"]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"