plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

neoForge {
    version = rootProject.neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
//    parchment {
//        minecraftVersion = rootProject.parchment_minecraft_version
//        mappingsVersion = rootProject.parchment_version
//    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            clientData()
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

//Use the existing Neoforge data generator for resource pack data
def generatedResources = project(":neoforge").file("src/generated/resources")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

repositories {
    maven { url "https://maven.neoforged.net/releases/" }
    maven { url "https://maven.architectury.dev/" }
}

dependencies {
//    neoForge "net.neoforged:neoforge:${neoforge_version}"
//
//    common(project(path: ":common", configuration: "namedElements")) { transitive false }
//    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive false }

    //Required for compiling as we use Cloth config for Fabric but reuse the same object for Neoforge native Config
    //We don't want to include Cloth config for the Neoforge version
//    modApi("me.shedaniel.cloth:cloth-config-neoforge:${rootProject.cloth_config_version}")

//    modCompileOnly "curse.maven:configured-457570:${rootProject.configured_version}"
//    modRuntimeOnly "curse.maven:configured-457570:${rootProject.configured_version}"
//    include "me.shedaniel.cloth:cloth-config-neoforge:${rootProject.cloth_config_version}"

}